###Get
GET {{baseUri}}/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}



###Create
POST {{baseUri}}/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "customer_id": 1,
  "status": "pending",
  "total": "150.50"
}


###Get
GET {{baseUri}}/orders/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###Update
PUT {{baseUri}}/orders/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "customer_id": 1,
  "status": "paid",
  "total": "150.50"
}

###Delete
DELETE {{baseUri}}/orders/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}