### index
GET {{baseUri}}/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}


### store
POST {{baseUri}}/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Produto Novo",
    "description": "Produto criado via API/REST"
    "price": 200.00
    "stock": 3
}

### show
GET {{baseUri}}/products/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### update
PUT {{baseUri}}/products/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "description": "Produto ATUALIZADO via API/REST"
}

### delete 
DELETE {{baseUri}}/products/6 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}